version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the current directory to /app in the container for live reloading
    env_file:
      - .env    # Load environment variables from .env file (to be created in subtask 1.3)
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" # Expose PostgreSQL port to host (optional, for direct DB access)
    environment:
      # These will be used if not overridden by .env file values passed to the 'web' service
      # and subsequently used by the application to connect to the DB.
      # For the db service itself, these set the initial superuser and database.
      POSTGRES_USER: ${POSTGRES_USER:-app_user} # Default to app_user if not set in .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # Default to password if not set in .env
      POSTGRES_DB: ${POSTGRES_DB:-christian_music_app}   # Default to christian_music_app if not set in .env
    restart: unless-stopped

volumes:
  postgres_data: # Persists database data across container restarts
