services:
  web:
    build:
      context: .
      network: host
    command: gunicorn --bind 0.0.0.0:5001 --workers 1 --timeout 1800 --worker-connections 100 run:app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
      - DEBUG=false
      - LLM_API_BASE_URL=http://localhost:11434/v1
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - TOKENIZERS_PARALLELISM=false
      - BACKFILL_WORKERS=3
      - BACKFILL_BATCH_SIZE=25
      - LLM_TIMEOUT=120
    depends_on:
      - db
      - redis
    restart: unless-stopped
    network_mode: "host"

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    network_mode: "host"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --save 60 1000
    restart: unless-stopped
    network_mode: "host"

volumes:
  postgres_data:
  redis_data:

