[tool.ruff]
line-length = 100
target-version = "py39"
extend-exclude = [
  ".venv",
  "migrations",
]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
  "E501",  # long lines in tests
  "F403",  # star imports in helpers
  "F405",  # names from star imports
  "F401",  # unused imports in test scaffolding
  "F841",  # assigned but never used
  "E722",  # bare except in test code
  "E402",  # module import not at top (test scaffolding)
  "F821",  # undefined names in mocks/annotations
  "F811",  # redefinition in param fixtures/tests
]
"validate_model_caching.py" = ["F841", "E501"]
"app/utils/database.py" = ["F811"]
"app/utils/health_monitor.py" = ["E722", "F841", "F821"]
"app/utils/function_instrumentation.py" = ["F841"]
"app/utils/lyrics/lyrics_fetcher.py" = ["F841"]
"app/utils/biblical_reference_detector.py" = ["F841"]
"scripts/**" = ["E501", "E711", "F841", "E402"]
"app/__init__.py" = ["F401"]
"app/models/__init__.py" = ["F403"]
"app/routes/api.py" = ["F841", "F821"]
"app/services/rules_rag.py" = ["E741"]
"app/utils/analysis/embedding_index.py" = ["E741"]
"app/utils/analysis/huggingface_analyzer.py" = ["F841"]
"regression_test.py" = ["F841", "E501"]

[tool.ruff.lint.isort]
known-first-party = ["app"]
