name: Bug report
description: Report a problem
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide steps, inputs, and observed outputs
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
  - type: input
    id: version
    attributes:
      label: Version/commit
