name: Feature request
description: Propose an enhancement
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet points of what “done” means
  - type: textarea
    id: context
    attributes:
      label: Context/alternatives
