"""Remove user analysis preferences table

Revision ID: 0953e4754acd
Revises: d8e43514823b
Create Date: 2025-05-24 15:06:25.044004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0953e4754acd'
down_revision = 'd8e43514823b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_analysis_preferences')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analysis_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('sensitivity_level', sa.String(20), nullable=False, server_default='moderate'),
        sa.Column('profanity_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('violence_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('sexual_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('drug_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('positive_boost', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('denominational_preferences', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', name='unique_user_preferences')
    )
    # ### end Alembic commands ###
