"""add v3.1 framework fields to analysis_results

Revision ID: 1d29840152fe
Revises: 8b4077e23bf1
Create Date: 2025-08-10 16:19:45.976737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d29840152fe'
down_revision = '8b4077e23bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verdict', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('purity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('formation_risk', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('doctrinal_clarity', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('narrative_voice', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('lament_filter_applied', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('framework_data', sa.JSON(), nullable=True))
        batch_op.create_index('idx_analysis_song_created', ['song_id', 'created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('analysis_results_song_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('playlist_songs_song_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('playlist_songs_playlist_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('playlist_songs_playlist_id_fkey'), 'playlists', ['playlist_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('playlist_songs_song_id_fkey'), 'songs', ['song_id'], ['id'])

    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('analysis_results_song_id_fkey'), 'songs', ['song_id'], ['id'])
        batch_op.drop_index('idx_analysis_song_created')
        batch_op.drop_column('framework_data')
        batch_op.drop_column('lament_filter_applied')
        batch_op.drop_column('narrative_voice')
        batch_op.drop_column('needs_review')
        batch_op.drop_column('confidence')
        batch_op.drop_column('doctrinal_clarity')
        batch_op.drop_column('formation_risk')
        batch_op.drop_column('purity_score')
        batch_op.drop_column('verdict')

    # ### end Alembic commands ###
