"""Add lyrics cache table

Revision ID: 37d30fcaa1f6
Revises: add_performance_indexes
Create Date: 2025-05-27 15:49:38.261673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d30fcaa1f6'
down_revision = 'add_performance_indexes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lyrics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist', 'title', name='uix_artist_title')
    )
    with op.batch_alter_table('lyrics_cache', schema=None) as batch_op:
        batch_op.create_index('idx_lyrics_cache_artist_title', ['artist', 'title'], unique=False)
        batch_op.create_index('idx_lyrics_cache_source', ['source'], unique=False)
        batch_op.create_index('idx_lyrics_cache_updated_at', ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_lyrics_cache_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_lyrics_cache_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lyrics_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lyrics_cache_title'))
        batch_op.drop_index(batch_op.f('ix_lyrics_cache_artist'))
        batch_op.drop_index('idx_lyrics_cache_updated_at')
        batch_op.drop_index('idx_lyrics_cache_source')
        batch_op.drop_index('idx_lyrics_cache_artist_title')

    op.drop_table('lyrics_cache')
    # ### end Alembic commands ###
