"""add track_count and total_tracks to playlists

Revision ID: 8b4077e23bf1
Revises: 37d30fcaa1f6
Create Date: 2025-06-01 16:25:37.114275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4077e23bf1'
down_revision = '37d30fcaa1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tracks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('total_tracks')
        batch_op.drop_column('track_count')
    # ### end Alembic commands ###
