"""Add album_art_url to Song model

Revision ID: 95c44ad3e472
Revises: 8de592b8260d
Create Date: 2025-05-12 16:04:59.617917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c44ad3e472'
down_revision = '8de592b8260d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_art_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('album_art_url')

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
