"""Add user analysis preferences

Revision ID: add_user_analysis_preferences
Revises: 0543cea91b5b
Create Date: 2025-05-24

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_user_analysis_preferences'
down_revision = '0543cea91b5b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analysis_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('sensitivity_level', sa.String(20), nullable=False, server_default='moderate'),
        sa.Column('profanity_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('violence_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('sexual_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('drug_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('positive_boost', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('denominational_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', name='unique_user_preferences')
    )

    # Create indexes
    op.create_index('idx_user_analysis_preferences_user_id', 'user_analysis_preferences', ['user_id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_analysis_preferences_user_id', table_name='user_analysis_preferences')
    op.drop_table('user_analysis_preferences')
    # ### end Alembic commands ###
