"""Add detailed analysis fields to AnalysisResult

Revision ID: d8e43514823b
Revises: 0cad2d21a349
Create Date: 2025-05-24 09:49:16.083336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8e43514823b'
down_revision = '0cad2d21a349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purity_flags_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('positive_themes_identified', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('biblical_themes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('supporting_scripture', sa.JSON(), nullable=True))

    with op.batch_alter_table('user_analysis_preferences', schema=None) as batch_op:
        batch_op.alter_column('denominational_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index('idx_user_analysis_preferences_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_analysis_preferences', schema=None) as batch_op:
        batch_op.create_index('idx_user_analysis_preferences_user_id', ['user_id'], unique=False)
        batch_op.alter_column('denominational_preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('supporting_scripture')
        batch_op.drop_column('biblical_themes')
        batch_op.drop_column('positive_themes_identified')
        batch_op.drop_column('purity_flags_details')

    # ### end Alembic commands ###
