"""Add duration_ms to Song model

Revision ID: ded7081c806b
Revises: f0c12b6fd5ea
Create Date: 2025-05-16 11:07:10.466274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded7081c806b'
down_revision = 'f0c12b6fd5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('duration_ms')

    # ### end Alembic commands ###
