"""Add raw_score and concern_level to AnalysisResult

Revision ID: f0c12b6fd5ea
Revises: 95c44ad3e472
Create Date: 2025-05-13 16:25:43.785080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c12b6fd5ea'
down_revision = '95c44ad3e472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('concern_level', sa.String(length=50), nullable=True))

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_synced_from_spotify', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('last_synced_from_spotify')

    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('concern_level')
        batch_op.drop_column('raw_score')

    # ### end Alembic commands ###
