name: CI Full
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 7 * * *"
jobs:
  full:
    runs-on: ubuntu-latest
    env:
      CI: "1"
      DISABLE_ANALYZER_PREFLIGHT: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip
      - run: pip install -r requirements.txt
      - run: make test

