name: CI Weekly (Full Suite)

on:
  schedule:
    - cron: '0 3 * * 1' # Weekly on Monday at 03:00 UTC
  workflow_dispatch: {}

jobs:
  full-tests:
    runs-on: ubuntu-latest
    env:
      FLASK_ENV: testing
      ENABLE_HF_ANALYZER: "0"          # Do not load HF models
      USE_LLM_ANALYZER: "1"            # Prefer main LLM analyzer path
      DISABLE_ZERO_SHOT: "1"           # Avoid heavy zero-shot model
      TRANSFORMERS_OFFLINE: "1"        # Prevent downloads
      HF_HUB_DISABLE_TELEMETRY: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.6.5

      - name: Lint (ruff)
        run: |
          ruff check --format=github .

      - name: Run full test suite (includes integration)
        run: |
          pytest -q
