name: CI Smoke
on:
  pull_request:
  push:
    branches: [ feature/**, fix/** ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      CI: "1"
      DISABLE_ANALYZER_PREFLIGHT: "1"
      LYRICS_DISABLE_NEGATIVE_CACHE: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
      - run: pip install -r requirements.txt
      - run: make test-smoke

