name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      FLASK_ENV: testing
      ENABLE_HF_ANALYZER: "0"
      USE_LLM_ANALYZER: "1"  # Force LLM path; code falls back safely in tests
      DISABLE_ZERO_SHOT: "1"  # Skip heavy zero-shot model
      TRANSFORMERS_OFFLINE: "1"  # Prevent downloads in CI
      HF_HUB_DISABLE_TELEMETRY: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.6.5

      - name: Lint (ruff blocking)
        run: |
          ruff --version
          ruff check --output-format=github .

      - name: Run tests (unit + fast)
        run: |
          pytest -q -m "not integration"
