name: PR Title Lint

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title for Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat, fix, chore, docs, style, refactor, perf, test, ci, build, revert
          scopes: |
            app, api, docs, infra, ci, tests
          requireScope: false
          subjectPattern: 
          subjectPatternError: ''

